version: '3'

services:
  mysql:
    container_name: mysql_house
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--charactor-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"