server.port: 9050

spring:
  output.ansi.enabled: always
  thymeleaf.check-template-location: false

  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true

  h2.console:
    enabled: true
    path: /h2-console